# Generated by Django 5.2.6 on 2025-09-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dni',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Cédula'),
        ),
    ]
