# Generated by Django 5.2.6 on 2025-09-14 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=12, unique=True)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Hidrologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_delhidrologica', models.CharField(max_length=150, verbose_name='Nombre de la hidrológica')),
                ('acronimo', models.CharField(max_length=20, verbose_name='Acrónimo')),
                ('rif', models.CharField(max_length=15, unique=True, verbose_name='RIF')),
                ('presidente_actual', models.CharField(max_length=100, verbose_name='Presidente actual')),
                ('ciclo_lectura', models.CharField(max_length=2, verbose_name='Ciclo de lectura')),
                ('direccion_ip_publica', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='IP pública')),
                ('direccion_ip_privada', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='IP privada')),
                ('tipo_conexion', models.CharField(choices=[('local', 'Local'), ('vpn', 'VPN')], max_length=10, verbose_name='Tipo de conexión')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('gerente_comercial_actual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidrologicas_gerente', to='hidrologicas.gerente')),
            ],
        ),
    ]
