# Generated by Django 5.2.6 on 2025-09-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidrologicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hidrologica',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='hidrologicas_logos/'),
        ),
    ]
