# Generated by Django 5.2.6 on 2025-09-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidrologicas', '0002_hidrologica_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hidrologica',
            name='direccion_ip_vpn',
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='IP VPN'),
        ),
    ]
