# Generated by Django 5.2.6 on 2025-09-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidrologicas', '0003_hidrologica_direccion_ip_vpn'),
    ]

    operations = [
        migrations.AddField(
            model_name='hidrologica',
            name='datacenter_hidroven',
            field=models.BooleanField(default=False, verbose_name='DataCenter - Hidroven'),
        ),
    ]
