# Generated by Django 5.2.6 on 2025-09-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidrologicas', '0004_hidrologica_datacenter_hidroven'),
    ]

    operations = [
        migrations.AddField(
            model_name='hidrologica',
            name='estado_conexion',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10, verbose_name='Estado de conexión'),
        ),
    ]
