# Generated by Django 5.2.6 on 2025-09-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidrologicas', '0005_hidrologica_estado_conexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='hidrologica',
            name='latencia_ms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Latencia (ms)'),
        ),
    ]
