# Generated by Django 5.2.6 on 2025-09-15 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hidrologicas', '0006_hidrologica_latencia_ms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hidrologica',
            name='gerente_comercial_actual',
        ),
        migrations.RemoveField(
            model_name='hidrologica',
            name='presidente_actual',
        ),
    ]
