# Generated by Django 5.2.6 on 2025-09-12 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carnet',
            options={'verbose_name': 'Carnet', 'verbose_name_plural': 'Carnets'},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='oficina',
            options={'verbose_name': 'Oficina', 'verbose_name_plural': 'Oficinas'},
        ),
        migrations.AlterModelOptions(
            name='piso',
            options={'verbose_name': 'Piso', 'verbose_name_plural': 'Pisos'},
        ),
        migrations.AlterModelOptions(
            name='visita',
            options={'verbose_name': 'Visita', 'verbose_name_plural': 'Visitas'},
        ),
        migrations.AlterModelOptions(
            name='visitante',
            options={'verbose_name': 'Visitante', 'verbose_name_plural': 'Visitantes'},
        ),
        migrations.AlterField(
            model_name='carnet',
            name='visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgv.visitante'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='piso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgv.piso'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='anfitrion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgv.empleado'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='carnet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgv.carnet'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='oficina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgv.oficina'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgv.visitante'),
        ),
        migrations.AlterModelTable(
            name='carnet',
            table='sgv.carnet',
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='sgv.empleado',
        ),
        migrations.AlterModelTable(
            name='oficina',
            table='sgv.oficina',
        ),
        migrations.AlterModelTable(
            name='piso',
            table='sgv.piso',
        ),
        migrations.AlterModelTable(
            name='visita',
            table='sgv.visita',
        ),
        migrations.AlterModelTable(
            name='visitante',
            table='sgv.visitante',
        ),
    ]
